import Head from "next/head";
import { Inter } from "next/font/google";

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>About</main>
    </>
  );
}

export async function getStaticProps(context: GetStaticPropsContext) {
  console.log("about call");

  return {
    props: {}, // will be passed to the page component as props
  };
}
