import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSidePropsContext, GetStaticPropsContext } from "next";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>About</main>
    </>
  );
}

export async function getStaticProps(context: GetStaticPropsContext) {
  console.log("about call");

  return {
    props: {}, // will be passed to the page component as props
  };
}
